CREATE TABLE IF NOT EXISTS orbitapi.categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    cor VARCHAR(10) NOT NULL,
    CONSTRAINT categorias_nome_preenchido CHECK (char_length(trim(nome)) >= 1),
    CONSTRAINT categorias_cor_check CHECK (cor IN ('AZUL', 'VERDE', 'AMARELO', 'LARANJA', 'VERMELHO', 'ROSA', 'ROXO', 'CIANO', 'CINZA'))
);

CREATE UNIQUE INDEX IF NOT EXISTS categorias_nome_unico ON orbitapi.categorias (lower(nome));

INSERT INTO orbitapi.categorias (nome, cor)
VALUES ('Estudos', 'ROXO'),
       ('Trabalho', 'AZUL'),
       ('Casa e família', 'VERDE'),
       ('Saúde', 'ROSA');