CREATE TABLE IF NOT EXISTS orbitapi.atividades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(40) NOT NULL,
    cor VARCHAR(10) NOT NULL,
    meta_semanal_minutos INTEGER,
    arquivada BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT atividades_nome_preenchido CHECK (char_length(trim(nome)) >= 1),
    CONSTRAINT atividades_cor_check CHECK (cor IN ('AZUL', 'VERDE', 'AMARELO', 'LARANJA', 'VERMELHO', 'ROSA', 'ROXO', 'CIANO', 'CINZA')),
    CONSTRAINT atividades_meta_semanal_check CHECK (meta_semanal_minutos BETWEEN 1 AND 6000)
);

CREATE UNIQUE INDEX IF NOT EXISTS atividades_nome_ativo_unico ON orbitapi.atividades (lower(nome)) WHERE NOT arquivada;