CREATE TABLE IF NOT EXISTS orbitapi.series_recorrencia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_inicial DATE NOT NULL,
    frequencia VARCHAR(15) NOT NULL,
    data_fim DATE,
    gerada_ate DATE NOT NULL,
    CONSTRAINT series_recorrencia_frequencia_check CHECK (frequencia IN ('DIARIA', 'DIAS_DA_SEMANA', 'SEMANAL', 'MENSAL', 'ANUAL')),
    CONSTRAINT series_recorrencia_data_fim_check CHECK (data_fim >= data_inicial)
);

CREATE TABLE IF NOT EXISTS orbitapi.series_recorrencia_dias (
    serie_id BIGINT NOT NULL REFERENCES orbitapi.series_recorrencia (id) ON DELETE CASCADE,
    dia_semana VARCHAR(10) NOT NULL,
    PRIMARY KEY (serie_id, dia_semana),
    CONSTRAINT series_recorrencia_dias_dia_semana_check CHECK (dia_semana IN ('DOMINGO', 'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO'))
);

CREATE TABLE IF NOT EXISTS orbitapi.tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(120) NOT NULL,
    descricao VARCHAR(2000),
    data DATE,
    dia_inteiro BOOLEAN NOT NULL DEFAULT FALSE,
    horario_inicio TIME,
    horario_fim TIME,
    prioridade VARCHAR(10) NOT NULL,
    situacao VARCHAR(15) NOT NULL,
    categoria_id BIGINT REFERENCES orbitapi.categorias (id) ON DELETE SET NULL,
    atividade_id BIGINT REFERENCES orbitapi.atividades (id) ON DELETE SET NULL,
    lembrete_minutos_antes INTEGER,
    serie_id BIGINT REFERENCES orbitapi.series_recorrencia (id),
    data_conclusao TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL,
    atualizado_em TIMESTAMPTZ NOT NULL,
    CONSTRAINT tarefas_titulo_preenchido CHECK (char_length(trim(titulo)) >= 1),
    CONSTRAINT tarefas_prioridade_check CHECK (prioridade IN ('BAIXA', 'MEDIA', 'ALTA', 'URGENTE')),
    CONSTRAINT tarefas_situacao_check CHECK (situacao IN ('PENDENTE', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA')),
    CONSTRAINT tarefas_horario_exige_data CHECK (horario_inicio IS NULL OR data IS NOT NULL),
    CONSTRAINT tarefas_horario_fim_check CHECK (horario_fim IS NULL OR (horario_inicio IS NOT NULL AND horario_fim > horario_inicio)),
    CONSTRAINT tarefas_lembrete_check CHECK (lembrete_minutos_antes IN (0, 5, 15, 30, 60)),
    CONSTRAINT tarefas_data_conclusao_check CHECK (data_conclusao IS NULL OR situacao = 'CONCLUIDA')
);

CREATE INDEX IF NOT EXISTS tarefas_data_idx ON orbitapi.tarefas (data);
CREATE INDEX IF NOT EXISTS tarefas_serie_idx ON orbitapi.tarefas (serie_id);
CREATE INDEX IF NOT EXISTS tarefas_categoria_idx ON orbitapi.tarefas (categoria_id);
CREATE INDEX IF NOT EXISTS tarefas_atividade_idx ON orbitapi.tarefas (atividade_id);

CREATE TABLE IF NOT EXISTS orbitapi.eventos_tarefa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(20) NOT NULL,
    tarefa_id BIGINT NOT NULL REFERENCES orbitapi.tarefas (id) ON DELETE CASCADE,
    titulo VARCHAR(120) NOT NULL,
    ocorrido_em TIMESTAMPTZ NOT NULL,
    anterior VARCHAR(15),
    novo VARCHAR(15),
    CONSTRAINT eventos_tarefa_tipo_check CHECK (tipo IN ('TAREFA_CRIADA', 'TAREFA_CONCLUIDA', 'TAREFA_CANCELADA', 'TAREFA_REABERTA', 'PRIORIDADE_ALTERADA', 'DATA_ALTERADA'))
);

CREATE INDEX IF NOT EXISTS eventos_tarefa_tarefa_idx ON orbitapi.eventos_tarefa (tarefa_id);
CREATE INDEX IF NOT EXISTS eventos_tarefa_ocorrido_em_idx ON orbitapi.eventos_tarefa (ocorrido_em);