CREATE TABLE IF NOT EXISTS orbitapi.sessoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atividade_id BIGINT NOT NULL REFERENCES orbitapi.atividades (id),
    tarefa_id BIGINT REFERENCES orbitapi.tarefas (id) ON DELETE SET NULL,
    modo VARCHAR(10) NOT NULL,
    origem VARCHAR(10) NOT NULL,
    inicio TIMESTAMPTZ NOT NULL,
    fim TIMESTAMPTZ NOT NULL,
    duracao_segundos INTEGER NOT NULL,
    ciclos_concluidos INTEGER,
    observacao VARCHAR(500),
    CONSTRAINT sessoes_modo_check CHECK (modo IN ('LIVRE', 'POMODORO')),
    CONSTRAINT sessoes_origem_check CHECK (origem IN ('CRONOMETRO', 'MANUAL')),
    CONSTRAINT sessoes_fim_check CHECK (fim >= inicio),
    CONSTRAINT sessoes_duracao_check CHECK (duracao_segundos BETWEEN 60 AND 86400),
    CONSTRAINT sessoes_ciclos_check CHECK (ciclos_concluidos IS NULL OR (ciclos_concluidos >= 0 AND modo = 'POMODORO'))
);

CREATE INDEX IF NOT EXISTS sessoes_inicio_idx ON orbitapi.sessoes (inicio);
CREATE INDEX IF NOT EXISTS sessoes_atividade_idx ON orbitapi.sessoes (atividade_id);
CREATE INDEX IF NOT EXISTS sessoes_tarefa_idx ON orbitapi.sessoes (tarefa_id);